name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make
  
  test:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: push_swap
       run: ./push_swap 3 2
